on:
    push:
      branches:
        - main
jobs:
    run_pull:
      name: run pull
      runs-on: ubuntu-latest
  
      steps:
        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              whoami

        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Build and run Docker containers
          run: |
                cd ${{ github.workspace }}
                docker-compose up -d